### ISSUE TITLE
integer timeseries data returning as decimals near their intended value

### ISSUE THREAD

**Issue by jkatofsky** [SoftwareDefinedBuildings/mortar#4]
There appears to be an issue with timeseries data that is supposed to be binary or an integer being returned as floating point values near their intended values.

For example, at 2018-06-07   22:30:00+00:00 in the jesse-turner-center timeseries data, the point with uuid "b998a5c4-379c-3dd7-9cdd-5a26e604f8f4", a Thermostat_Mode_Command, hits the value 2.984210526 instead of 3, which seems out of place for a command point.

This can also be seen with on_off type points, which occasionally take timeseries values of decimals very close to 0.0.

**Comment by gtfierro** [comment]
Hi!

This is most likely happening because your query is using `mean` to aggregate multiple readings in the same window, which can result in non-integer values. If you want the true integer values, consider using `max` or `min` or even `raw`. 

For example

```python
thermostat_status_streams = pymortar.DataFrame(
    name="thermostat_status_data",
    aggregation=pymortar.MAX, # <-- here is the aggregation function
    window="1m",
    timeseries=[
        pymortar.Timeseries(
            view="tstat_points",
            dataVars=["?state"]
        )
    ]
)
```

For the meanings of the integer values, you can consult [this document](https://github.com/gtfierro/xboswave/blob/master/proto/nullabletypes.proto#L43-L56).

Hope that helps1

**Comment by jkatofsky** [comment]
@gtfierro ah! I hadn't considered that at all. Thanks!
